require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SweepstakesController do

  # This should return the minimal set of attributes required to create a valid
  # Sweepstake. As you add validations to Sweepstake, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SweepstakesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sweepstakes as @sweepstakes" do
      sweepstake = Sweepstake.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sweepstakes).should eq([sweepstake])
    end
  end

  describe "GET show" do
    it "assigns the requested sweepstake as @sweepstake" do
      sweepstake = Sweepstake.create! valid_attributes
      get :show, {:id => sweepstake.to_param}, valid_session
      assigns(:sweepstake).should eq(sweepstake)
    end
  end

  describe "GET new" do
    it "assigns a new sweepstake as @sweepstake" do
      get :new, {}, valid_session
      assigns(:sweepstake).should be_a_new(Sweepstake)
    end
  end

  describe "GET edit" do
    it "assigns the requested sweepstake as @sweepstake" do
      sweepstake = Sweepstake.create! valid_attributes
      get :edit, {:id => sweepstake.to_param}, valid_session
      assigns(:sweepstake).should eq(sweepstake)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sweepstake" do
        expect {
          post :create, {:sweepstake => valid_attributes}, valid_session
        }.to change(Sweepstake, :count).by(1)
      end

      it "assigns a newly created sweepstake as @sweepstake" do
        post :create, {:sweepstake => valid_attributes}, valid_session
        assigns(:sweepstake).should be_a(Sweepstake)
        assigns(:sweepstake).should be_persisted
      end

      it "redirects to the created sweepstake" do
        post :create, {:sweepstake => valid_attributes}, valid_session
        response.should redirect_to(Sweepstake.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sweepstake as @sweepstake" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sweepstake.any_instance.stub(:save).and_return(false)
        post :create, {:sweepstake => {}}, valid_session
        assigns(:sweepstake).should be_a_new(Sweepstake)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sweepstake.any_instance.stub(:save).and_return(false)
        post :create, {:sweepstake => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sweepstake" do
        sweepstake = Sweepstake.create! valid_attributes
        # Assuming there are no other sweepstakes in the database, this
        # specifies that the Sweepstake created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sweepstake.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sweepstake.to_param, :sweepstake => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sweepstake as @sweepstake" do
        sweepstake = Sweepstake.create! valid_attributes
        put :update, {:id => sweepstake.to_param, :sweepstake => valid_attributes}, valid_session
        assigns(:sweepstake).should eq(sweepstake)
      end

      it "redirects to the sweepstake" do
        sweepstake = Sweepstake.create! valid_attributes
        put :update, {:id => sweepstake.to_param, :sweepstake => valid_attributes}, valid_session
        response.should redirect_to(sweepstake)
      end
    end

    describe "with invalid params" do
      it "assigns the sweepstake as @sweepstake" do
        sweepstake = Sweepstake.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sweepstake.any_instance.stub(:save).and_return(false)
        put :update, {:id => sweepstake.to_param, :sweepstake => {}}, valid_session
        assigns(:sweepstake).should eq(sweepstake)
      end

      it "re-renders the 'edit' template" do
        sweepstake = Sweepstake.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sweepstake.any_instance.stub(:save).and_return(false)
        put :update, {:id => sweepstake.to_param, :sweepstake => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sweepstake" do
      sweepstake = Sweepstake.create! valid_attributes
      expect {
        delete :destroy, {:id => sweepstake.to_param}, valid_session
      }.to change(Sweepstake, :count).by(-1)
    end

    it "redirects to the sweepstakes list" do
      sweepstake = Sweepstake.create! valid_attributes
      delete :destroy, {:id => sweepstake.to_param}, valid_session
      response.should redirect_to(sweepstakes_url)
    end
  end

end
